### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by SHALLSHADOWS** [petscaramussi/helpDesk#1]
Hello, I have successfully deployed the project, but I don't know how to proceed with logging in. Could you assist me?

**Comment by petscaramussi** [comment]
When I did the project, it was intended for each user to have their own predefined login. There's no route for 'register'; you have to do it manually in the database :(

I know this is not the best way to do that.

**Comment by SHALLSHADOWS** [comment]
Alright, I see. Thanks for the assistance. I was able to log in, and by the way, it's a very good project. thanks for sharing .

**Comment by petscaramussi** [comment]
Thank you, that really motivates me!
